package cz.vutbr.fit.pdb.gui;

import java.awt.Container;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author Doma
 */
public class PrehledRezervaci extends javax.swing.JPanel {

    /**
     * Creates new form PrehledRezervaci
     */
    public PrehledRezervaci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        novaRezervace_button = new javax.swing.JButton();

        novaRezervace_button.setText("Nová rezervace");
        novaRezervace_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaRezervace_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(novaRezervace_button)
                .addGap(0, 560, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(novaRezervace_button)
                .addGap(0, 503, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void novaRezervace_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaRezervace_buttonActionPerformed
        JFrame frame = new JFrame("Nova rezervace");
        Rezervace rez = new Rezervace();
        rez.setParentFrame(frame);
        Container con = frame.getContentPane();
        con.add(rez);
        frame.setPreferredSize(new Dimension(761, 700));
        //frame.dispose();
        frame.setVisible(true);
        frame.pack();             
    }//GEN-LAST:event_novaRezervace_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novaRezervace_button;
    // End of variables declaration//GEN-END:variables
}
